---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${DEMODRA_API_REPO}
  triggers:
  - type: commit
  properties:
  - name: LOGICAL_APP_NAME
    value: ${LOGICAL_APP_NAME}
    type: text
  - name: BUILD_PREFIX
    value: master
    type: text
  jobs:
  - name: Build
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |-
      #!/bin/bash
      export PATH=/opt/IBM/node-v4.2/bin:$PATH
      npm install
      grunt dev-setup --no-color
  - name: Unit Test and Code Coverage
    type: tester
    enable_tests: true
    test_file_pattern: ./mochatest.xml
    coverage_type: istanbul
    coverage_directory: ./tests/coverage/reports/lcov-report
    coverage_file_pattern: ./tests/coverage/reports/coverage.json
    script: |-
      #!/bin/bash
      export PATH=/opt/IBM/node-v4.2/bin:$PATH
      npm install
      npm install -g grunt-idra3

      set +e
      grunt dev-test-cov --no-color
      grunt_result=$?
      set -e

      idra --publishtestresult --filelocation=./mochatest.xml --type=unittest
      idra --publishtestresult --filelocation=./tests/coverage/reports/coverage-summary.json --type=code

      if [ $grunt_result -ne 0 ]; then
         exit $grunt_result
      fi
